# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sacco?useSSL=false&serverTimezone=Africa/Nairobi&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
spring.datasource.username=ogesa
spring.datasource.password=ogesa123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Local configuration
app.security.cookie-secure=false
app.security.cors-origins=http://localhost:5173

mpesa.sandbox=true
mpesa.consumer-key=CvlkedQiKT7VCs5PqDN23XoLGDUblyBRbuyEoUjYKVbe6S8m
mpesa.consumer-secret=rcppKAxNbpFOrACTacwoOqywRXLHKHMeF5eEhYzXbBV4GrRPKhfD8cEGDMeBmb7D
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.paybill=174379
mpesa.base-url=https://sandbox.safaricom.co.ke
mpesa.stk-callback-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/stk/callback
mpesa.c2b-confirmation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/confirmation
mpesa.c2b-validation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/validation