# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sacco?useSSL=false&serverTimezone=Africa/Nairobi&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
spring.datasource.username=ogesa
spring.datasource.password=ogesa123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Local configuration
app.security.cookie-secure=false
app.security.cors-origins=http://localhost:5173

logging.file.name=app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.com.example.acacia=INFO

mpesa.sandbox=true
mpesa.consumer-key=CvlkedQiKT7VCs5PqDN23XoLGDUblyBRbuyEoUjYKVbe6S8m
mpesa.consumer-secret=rcppKAxNbpFOrACTacwoOqywRXLHKHMeF5eEhYzXbBV4GrRPKhfD8cEGDMeBmb7D
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.paybill=174379
mpesa.base-url=https://sandbox.safaricom.co.ke
mpesa.stk-callback-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/stk/callback
mpesa.c2b-confirmation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/confirmation
mpesa.c2b-validation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/validation

mpesa.b2c-security-credential=fMFxr078GO/wQcMBkt1ggkHYDJpD01DJ9jB7QcIJrJrTuQaAZFWU63CRZk+jJAAIvid8sihOfYR6OoXqHBRHcYynnrehuNghQdjKWjNm9xRxz7qRue/GPyR6zG1QU0l65l2o4unCN1ZrM96jJO2UScu2PSIQgHBc78XGAEll77BnQ29hzIo4rjNKO38CrxhijxOZrvKY46gV/IHBlmFLM7VSfT9EyKWqVrukCdqdc57sDn/dP4P73GO+sF1/+9Cgr//mZa/ZKvOS8x5lldo7TAxTMg4rhMHTnwy7CpoRsYVvugbvU9svrFna9YrtM7miVTTtXoVZOBDeWCBdZpZYLw==
mpesa.initiator-name=testapi
mpesa.b2c-shortcode=600999
mpesa.b2c-result-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/b2c/result
mpesa.b2c-timeout-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/b2c/timeout
mpesa.balance-result-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/balance/result
mpesa.balance-timeout-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/balance/timeout