# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sacco?useSSL=false&serverTimezone=Africa/Nairobi&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
spring.datasource.username=ogesa
spring.datasource.password=ogesa123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Local configuration
app.security.cookie-secure=false
app.security.cors-origins=http://localhost:5173

mpesa.sandbox=true
mpesa.consumer-key=CvlkedQiKT7VCs5PqDN23XoLGDUblyBRbuyEoUjYKVbe6S8m
mpesa.consumer-secret=rcppKAxNbpFOrACTacwoOqywRXLHKHMeF5eEhYzXbBV4GrRPKhfD8cEGDMeBmb7D
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.paybill=174379
mpesa.base-url=https://sandbox.safaricom.co.ke
mpesa.stk-callback-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/stk/callback
mpesa.c2b-confirmation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/confirmation
mpesa.c2b-validation-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/c2b/validation

mpesa.b2c-security-credential=MknSnb5PTdcdaYgGmBjvJ2bYoTl6VgCPJbMc3HIeMC/LzAwWMi1roM+qXHYg37ndJ7vTdxJDLsRgqkEhxfCUYAKWi7ysg8v6TwUVBBMxNlIcWe58AjMN8u22QwlvVJ1unytRRnyt8swZaONsjsBRj82Zl8+MCxWqDAt48zXT425QioFqd9tGm/Y5F6Q7KHhzYr3qJZ/6rRoAvyynT2Bwo0zlwERySv8VYwCe1/iknUIaZEpp/+sf5Pfi20hKUplugxcc++7FGK3pzjWwHaabLH72IvgkU7gZIxH6P2USlDIkQORr4/Ga7xYkzXYr42PXTmFbBBhoI7Es7nrWYyPx7A==
mpesa.initiator-name=testapi
mpesa.b2c-shortcode=600999
mpesa.b2c-result-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/b2c/result
mpesa.b2c-timeout-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/b2c/timeout
mpesa.balance-result-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/balance/result
mpesa.balance-timeout-url=https://quizzical-chaya-dullishly.ngrok-free.dev/api/v1/mpesa-callbacks/balance/timeout