package com.example.acacia.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "contributions", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"member_id", "period_id"})
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Contribution {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

    @ManyToOne
    @JoinColumn(name = "period_id")
    private ContributionPeriod period;

    private BigDecimal amount;
    private LocalDateTime paymentDate;
    private boolean isLate;
    private boolean autoGenerated;
}
