package com.example.acacia.service;

import com.example.acacia.enums.*;
import com.example.acacia.model.*;
import com.example.acacia.repository.*;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class ContributionPenaltyJobService {

    private final ContributionPeriodRepository periodRepository;
    private final MemberRepository memberRepository;
    private final ContributionRepository contributionRepository;
    private final FineRepository fineRepository;
    private final SaccoSetupRepository saccoSetupRepository;
    private final ContributionArrearRepository contributionArrearRepository;
    private final CreditScoreService creditScoreService;
    private final ExtraRepository extraRepository;

    @Scheduled(cron = "0 5 18 ? * SAT") // Saturday 6:05 PM
    @Transactional
    public void applyLateContributionFines() {

        SaccoSetups setup = saccoSetupRepository.findByStatus(SetupStatus.ACTIVE);

        //find the latest period
//        ContributionPeriod currentPeriod =
//                periodRepository.findByDate(
//                        LocalDate.now().minusDays(setup.getDaysToDeadline())
//                );

        ContributionPeriod currentPeriod = periodRepository.findAll().getLast();

        if (currentPeriod == null) return;

        for (Member member : memberRepository.findAllByStatus(MemberStatus.ACTIVE)) {

            boolean contributed = contributionRepository
                    .existsByMemberAndPeriod(member, currentPeriod);

            if (contributed) continue;

            BigDecimal contributionAmount = setup.getContributionAmount();

            // 1️⃣ Get total surplus
            List<Extra> surplusList =
                    extraRepository.findByMemberAndTypeAndStatus(
                            member,
                            ExtraType.SURPLUS,
                            ExtraStatus.ACTIVE
                    );

            BigDecimal totalSurplus = surplusList.stream()
                    .map(Extra::getAmount)
                    .reduce(BigDecimal.ZERO, BigDecimal::add);

            BigDecimal amountCovered = totalSurplus.min(contributionAmount);
            BigDecimal balance = contributionAmount.subtract(amountCovered);

            // 2️⃣ If surplus exists, auto-record contribution
            if (amountCovered.compareTo(BigDecimal.ZERO) > 0) {

                Contribution autoContribution = Contribution.builder()
                        .member(member)
                        .period(currentPeriod)
                        .amount(amountCovered)
                        .paymentDate(LocalDateTime.now())
                        .autoGenerated(true)
                        .build();

                contributionRepository.save(autoContribution);

                // 3️⃣ Deduct surplus FIFO
                BigDecimal remaining = amountCovered;

                for (Extra surplus : surplusList) {
                    if (remaining.compareTo(BigDecimal.ZERO) <= 0) break;

                    BigDecimal deduction =
                            surplus.getAmount().min(remaining);

                    surplus.setAmount(surplus.getAmount().subtract(deduction));

                    if (surplus.getAmount().compareTo(BigDecimal.ZERO) == 0) {
                        surplus.setStatus(ExtraStatus.SETTLED);
                    }

                    extraRepository.save(surplus);
                    remaining = remaining.subtract(deduction);
                }
            }

            // 4️⃣ If still balance → fine + arrear
            if (balance.compareTo(BigDecimal.ZERO) > 0) {

                Fine fine = Fine.builder()
                        .member(member)
                        .amount(setup.getLatePaymentFineAmount())
                        .status(FineStatus.UNPAID)
                        .type(FineTyp.LATE_PAYMENT)
                        .fineDate(LocalDate.now())
                        .build();

                Fine savedFine = fineRepository.save(fine);

                ContributionArrear arrear = ContributionArrear.builder()
                        .member(member)
                        .period(currentPeriod)
                        .amount(balance)
                        .fine(savedFine)
                        .build();

                contributionArrearRepository.save(arrear);

                creditScoreService.updateCreditScore(member);
            }
        }
    }


}
